# Generated by Django 3.2 on 2021-04-24 10:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='None', help_text='Enter Unit', max_length=100, unique=True, verbose_name='品牌')),
            ],
            options={
                'verbose_name': '品牌',
                'verbose_name_plural': '品牌',
            },
        ),
        migrations.CreateModel(
            name='Keeper',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='None', help_text='Enter Keeper', max_length=100, unique=True, verbose_name='管理人')),
            ],
            options={
                'verbose_name': '管理人',
                'verbose_name_plural': '管理人',
            },
        ),
        migrations.CreateModel(
            name='LeaseHistory',
            fields=[
                ('return_date', models.DateTimeField(auto_created=True, default=django.utils.timezone.now, verbose_name='歸還日期')),
                ('agree_date', models.DateTimeField(auto_created=True, default=django.utils.timezone.now, verbose_name='同意日期')),
                ('borrow_date', models.DateTimeField(auto_created=True, default=django.utils.timezone.now, verbose_name='借用日期')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('leaseProperty', models.CharField(default='', help_text='財產名稱', max_length=100, verbose_name='財產')),
                ('leasePropertyID', models.IntegerField(default=1, help_text='財產ID', verbose_name='財產ID')),
                ('borrower', models.CharField(default='', help_text='借用者名稱', max_length=100, verbose_name='借用者')),
                ('borrow_administrator', models.CharField(default='', help_text='借用管理員名稱', max_length=100, verbose_name='借用管理員')),
                ('returner', models.CharField(default='', help_text='歸還者名稱', max_length=100, verbose_name='歸還者')),
                ('returner_administrator', models.CharField(default='', help_text='歸還管理員名稱', max_length=100, verbose_name='歸還管理員')),
            ],
            options={
                'verbose_name': '租借歷史',
                'verbose_name_plural': '租借歷史紀錄',
                'ordering': ['borrow_date'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='None', help_text='Enter Postion', max_length=100, unique=True, verbose_name='位置')),
            ],
            options={
                'verbose_name': '位置',
                'verbose_name_plural': '位置',
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('image_name', models.CharField(default='None', help_text='Enter Image Name', max_length=100, unique=True, verbose_name='財產圖片名稱')),
                ('image', models.ImageField(upload_to='static/PropertyImage', verbose_name='財產圖片')),
            ],
            options={
                'verbose_name': '財產圖片',
                'verbose_name_plural': '財產圖片',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='None', help_text='Enter Unit', max_length=100, unique=True, verbose_name='單位')),
            ],
            options={
                'verbose_name': '單位',
                'verbose_name_plural': '單位',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('fill_date', models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='填寫日期')),
                ('get_date', models.DateField(auto_created=True, default=django.utils.timezone.now, help_text='The day that you get the property', verbose_name='獲取日期')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('check', models.CharField(choices=[('v', 'Checked'), ('x', 'NotChecked')], default='x', help_text='Property is checked', max_length=1, verbose_name='盤點')),
                ('property_number', models.CharField(default='', help_text='Enter property number', max_length=50, verbose_name='財產編號')),
                ('serial_number', models.CharField(help_text='Enter serial number', max_length=50, verbose_name='序號')),
                ('name', models.CharField(help_text='Enter property name', max_length=100, verbose_name='財產名稱')),
                ('expiry_date', models.PositiveIntegerField(default=1, help_text='years', verbose_name='年限')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='數量')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='價格')),
                ('tips', models.TextField(blank=True, default='', null=True, verbose_name='Tips')),
                ('status', models.CharField(choices=[('o', 'On loan'), ('a', 'Available'), ('r', 'Reserved')], default='a', help_text='Property availability', max_length=1, verbose_name='現在狀態')),
                ('brand', models.ForeignKey(default=1, help_text='Choose Brand', on_delete=django.db.models.deletion.PROTECT, to='index.brand', verbose_name='品牌')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='index.propertyimage', verbose_name='財產圖片')),
                ('keeper', models.ForeignKey(default=1, help_text='Choose Keeper', on_delete=django.db.models.deletion.PROTECT, to='index.keeper', verbose_name='管理人')),
                ('label_position', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='label_position', to='index.position', verbose_name='產貼位置')),
                ('position', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='position', to='index.position', verbose_name='位置')),
                ('quantity_unit', models.ForeignKey(default=1, help_text='Choose Quantity Unit', on_delete=django.db.models.deletion.PROTECT, to='index.unit', verbose_name='單位')),
            ],
            options={
                'verbose_name': '財產信息',
                'verbose_name_plural': '財產',
                'ordering': ['serial_number'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('action_date', models.DateTimeField(auto_created=True, default=django.utils.timezone.now, verbose_name='動作日期')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('n', 'notknown'), ('d', 'deleteData'), ('a', 'addData'), ('w', 'writeData'), ('l', 'loanProperty'), ('r', 'ReturnProperty'), ('i', 'importExcel'), ('y', 'agreeLoan'), ('x', 'notAgreeLoan')], default='n', max_length=1, verbose_name='用戶動作')),
                ('status', models.CharField(choices=[('r', 'Read'), ('n', 'notRead')], default='n', max_length=1, verbose_name='訊息狀態')),
                ('group_status', models.CharField(choices=[('r', 'Read'), ('n', 'notRead')], default='n', max_length=1, verbose_name='群體訊息狀態')),
                ('action_user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用戶')),
                ('notify_group', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.group', verbose_name='群組')),
            ],
        ),
        migrations.CreateModel(
            name='LeaseProperty',
            fields=[
                ('return_date', models.DateTimeField(auto_created=True, blank=True, null=True, verbose_name='歸還日期')),
                ('agree_date', models.DateTimeField(auto_created=True, blank=True, null=True, verbose_name='同意日期')),
                ('borrow_date', models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='借用日期')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('borrower', models.CharField(help_text='借用者名稱', max_length=100, verbose_name='借用者')),
                ('borrow_administrator', models.CharField(blank=True, help_text='借用管理員名稱', max_length=100, null=True, verbose_name='借用管理員')),
                ('returner', models.CharField(blank=True, help_text='歸還者名稱', max_length=100, null=True, verbose_name='歸還者')),
                ('returner_administrator', models.CharField(blank=True, help_text='歸還管理員名稱', max_length=100, null=True, verbose_name='歸還管理員')),
                ('status', models.CharField(choices=[('w', 'Waiting'), ('l', 'Loaning'), ('c', 'checkReturn'), ('r', 'Returned')], default='w', help_text='Now Status', max_length=1, verbose_name='現在狀態')),
                ('leaseProperty', models.ForeignKey(default=1, help_text='Choose Property', on_delete=django.db.models.deletion.CASCADE, to='index.property', verbose_name='財產')),
            ],
            options={
                'verbose_name': '租借',
                'verbose_name_plural': '租借清單',
                'ordering': ['borrow_date'],
            },
        ),
    ]
