# Generated by Django 3.1.7 on 2021-03-26 08:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='None', help_text='Enter Unit', max_length=100, unique=True, verbose_name='品牌')),
            ],
            options={
                'verbose_name': '品牌',
                'verbose_name_plural': '品牌',
            },
        ),
        migrations.CreateModel(
            name='Keeper',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='None', help_text='Enter Keeper', max_length=100, unique=True, verbose_name='管理人')),
            ],
            options={
                'verbose_name': '管理人',
                'verbose_name_plural': '管理人',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='None', help_text='Enter Postion', max_length=100, unique=True, verbose_name='位置')),
            ],
            options={
                'verbose_name': '位置',
                'verbose_name_plural': '位置',
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('image_name', models.CharField(default='None', help_text='Enter Image Name', max_length=100, unique=True, verbose_name='財產圖片名稱')),
                ('image', models.ImageField(upload_to='PropertyImage', verbose_name='財產圖片')),
            ],
            options={
                'verbose_name': '財產圖片',
                'verbose_name_plural': '財產圖片',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='None', help_text='Enter Unit', max_length=100, unique=True, verbose_name='單位')),
            ],
            options={
                'verbose_name': '單位',
                'verbose_name_plural': '單位',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('fill_date', models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='填寫日期')),
                ('get_date', models.DateField(auto_created=True, default=django.utils.timezone.now, help_text='The day that you get the property', verbose_name='獲取日期')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('check', models.CharField(choices=[('v', 'Checked'), ('x', 'NotChecked')], default='x', help_text='Property is checked', max_length=1, verbose_name='盤點')),
                ('property_number', models.CharField(default='', help_text='Enter property number', max_length=50, verbose_name='財產編號')),
                ('serial_number', models.CharField(help_text='Enter serial number', max_length=50, verbose_name='序號')),
                ('name', models.CharField(help_text='Enter property name', max_length=100, verbose_name='財產名稱')),
                ('expiry_date', models.PositiveIntegerField(default=1, help_text='years', verbose_name='年限')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='數量')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='價格')),
                ('tips', models.TextField(blank=True, default='', null=True, verbose_name='Tips')),
                ('status', models.CharField(choices=[('o', 'On loan'), ('a', 'Available'), ('r', 'Reserved')], default='a', help_text='Property availability', max_length=1, verbose_name='現在狀態')),
                ('brand', models.ForeignKey(default=1, help_text='Choose Brand', on_delete=django.db.models.deletion.PROTECT, to='index.brand', verbose_name='品牌')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='index.propertyimage', verbose_name='財產圖片')),
                ('keeper', models.ForeignKey(default=1, help_text='Choose Keeper', on_delete=django.db.models.deletion.PROTECT, to='index.keeper', verbose_name='管理人')),
                ('label_position', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='label_position', to='index.position', verbose_name='產貼位置')),
                ('position', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='position', to='index.position', verbose_name='位置')),
                ('quantity_unit', models.ForeignKey(default=1, help_text='Choose Quantity Unit', on_delete=django.db.models.deletion.PROTECT, to='index.unit', verbose_name='單位')),
            ],
            options={
                'verbose_name': '財產信息',
                'verbose_name_plural': '財產',
                'ordering': ['serial_number'],
            },
        ),
    ]
