# Generated by Django 3.2 on 2021-04-28 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='keeper',
            field=models.ForeignKey(blank=True, help_text='Choose Keeper', null=True, on_delete=django.db.models.deletion.SET_NULL, to='index.keeper', verbose_name='管理人'),
        ),
    ]
