# Generated by Django 3.1.7 on 2021-04-04 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyimage',
            name='image',
            field=models.ImageField(upload_to='static/PropertyImage', verbose_name='財產圖片'),
        ),
    ]
