# Generated by Django 3.1.7 on 2021-04-05 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20210404_2242'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaseProperty',
            fields=[
                ('return_date', models.DateTimeField(auto_created=True, verbose_name='歸還日期')),
                ('agree_date', models.DateTimeField(auto_created=True, verbose_name='同意日期')),
                ('borrow_date', models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='借用日期')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('borrower', models.CharField(help_text='借用者名稱', max_length=100, verbose_name='借用者')),
                ('borrow_administrator', models.CharField(help_text='借用管理員名稱', max_length=100, verbose_name='借用管理員')),
                ('returner', models.CharField(help_text='歸還者名稱', max_length=100, verbose_name='歸還者')),
                ('returner_administrator', models.CharField(help_text='歸還管理員名稱', max_length=100, verbose_name='歸還管理員')),
                ('leaseProperty', models.ForeignKey(default=1, help_text='Choose Property', on_delete=django.db.models.deletion.CASCADE, to='index.property', verbose_name='財產')),
            ],
        ),
    ]
