# Generated by Django 3.2 on 2021-05-08 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('index', '0002_alter_property_keeper'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentCheckProperty',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('v', 'Checked'), ('x', 'NotChecked'), ('m', 'Missing'), ('b', 'Broken'), ('o', 'Obsolete')], default='x', max_length=1, verbose_name='當前盤點物品狀態')),
                ('action_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='用戶')),
                ('prop', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='index.property', verbose_name='產品')),
            ],
        ),
    ]
