# Generated by Django 3.1.7 on 2021-04-05 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_leaseproperty'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaseproperty',
            options={'ordering': ['borrow_date'], 'verbose_name': '租借', 'verbose_name_plural': '租借清單'},
        ),
        migrations.AlterField(
            model_name='leaseproperty',
            name='borrow_administrator',
            field=models.CharField(help_text='借用管理員名稱', max_length=100, null=True, verbose_name='借用管理員'),
        ),
        migrations.AlterField(
            model_name='leaseproperty',
            name='returner',
            field=models.CharField(help_text='歸還者名稱', max_length=100, null=True, verbose_name='歸還者'),
        ),
        migrations.AlterField(
            model_name='leaseproperty',
            name='returner_administrator',
            field=models.CharField(help_text='歸還管理員名稱', max_length=100, null=True, verbose_name='歸還管理員'),
        ),
    ]
