# Generated by Django 3.1.7 on 2021-04-05 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20210405_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaseproperty',
            name='borrow_administrator',
            field=models.CharField(blank=True, help_text='借用管理員名稱', max_length=100, null=True, verbose_name='借用管理員'),
        ),
        migrations.AlterField(
            model_name='leaseproperty',
            name='returner',
            field=models.CharField(blank=True, help_text='歸還者名稱', max_length=100, null=True, verbose_name='歸還者'),
        ),
        migrations.AlterField(
            model_name='leaseproperty',
            name='returner_administrator',
            field=models.CharField(blank=True, help_text='歸還管理員名稱', max_length=100, null=True, verbose_name='歸還管理員'),
        ),
    ]
