# Generated by Django 3.1.7 on 2021-04-05 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_auto_20210405_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaseproperty',
            name='status',
            field=models.CharField(choices=[('w', 'Wating'), ('l', 'Loaning'), ('r', 'Returned')], default='w', help_text='Now Status', max_length=1, verbose_name='現在狀態'),
        ),
    ]
