# Generated by Django 3.1.7 on 2021-04-05 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_leaseproperty_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaseproperty',
            name='agree_date',
            field=models.DateTimeField(auto_created=True, blank=True, null=True, verbose_name='同意日期'),
        ),
        migrations.AlterField(
            model_name='leaseproperty',
            name='return_date',
            field=models.DateTimeField(auto_created=True, blank=True, null=True, verbose_name='歸還日期'),
        ),
    ]
