# Generated by Django 3.1.7 on 2021-04-06 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_auto_20210405_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaseproperty',
            name='status',
            field=models.CharField(choices=[('w', 'Waiting'), ('l', 'Loaning'), ('c', 'checkReturn'), ('r', 'Returned')], default='w', help_text='Now Status', max_length=1, verbose_name='現在狀態'),
        ),
    ]
