# Generated by Django 3.1.7 on 2021-04-08 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_auto_20210406_2054'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaseHistory',
            fields=[
                ('return_date', models.DateTimeField(auto_created=True, blank=True, null=True, verbose_name='歸還日期')),
                ('agree_date', models.DateTimeField(auto_created=True, blank=True, null=True, verbose_name='同意日期')),
                ('borrow_date', models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='借用日期')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('leaseProperty', models.CharField(help_text='財產名稱', max_length=100, verbose_name='財產')),
                ('borrower', models.CharField(help_text='借用者名稱', max_length=100, verbose_name='借用者')),
                ('borrow_administrator', models.CharField(blank=True, help_text='借用管理員名稱', max_length=100, null=True, verbose_name='借用管理員')),
                ('returner', models.CharField(blank=True, help_text='歸還者名稱', max_length=100, null=True, verbose_name='歸還者')),
                ('returner_administrator', models.CharField(blank=True, help_text='歸還管理員名稱', max_length=100, null=True, verbose_name='歸還管理員')),
            ],
            options={
                'verbose_name': '租借歷史',
                'verbose_name_plural': '租借歷史紀錄',
                'ordering': ['borrow_date'],
            },
        ),
    ]
