# Generated by Django 3.1.7 on 2021-04-08 12:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_leasehistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leasehistory',
            name='agree_date',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2021, 4, 8, 12, 12, 20, 500810, tzinfo=utc), verbose_name='同意日期'),
        ),
        migrations.AlterField(
            model_name='leasehistory',
            name='borrow_administrator',
            field=models.CharField(default='', help_text='借用管理員名稱', max_length=100, verbose_name='借用管理員'),
        ),
        migrations.AlterField(
            model_name='leasehistory',
            name='borrow_date',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2021, 4, 8, 12, 12, 20, 500810, tzinfo=utc), verbose_name='借用日期'),
        ),
        migrations.AlterField(
            model_name='leasehistory',
            name='borrower',
            field=models.CharField(default='', help_text='借用者名稱', max_length=100, verbose_name='借用者'),
        ),
        migrations.AlterField(
            model_name='leasehistory',
            name='leaseProperty',
            field=models.CharField(default='', help_text='財產名稱', max_length=100, verbose_name='財產'),
        ),
        migrations.AlterField(
            model_name='leasehistory',
            name='return_date',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2021, 4, 8, 12, 12, 20, 500810, tzinfo=utc), verbose_name='歸還日期'),
        ),
        migrations.AlterField(
            model_name='leasehistory',
            name='returner',
            field=models.CharField(default='', help_text='歸還者名稱', max_length=100, verbose_name='歸還者'),
        ),
        migrations.AlterField(
            model_name='leasehistory',
            name='returner_administrator',
            field=models.CharField(default='', help_text='歸還管理員名稱', max_length=100, verbose_name='歸還管理員'),
        ),
    ]
