# Generated by Django 3.2 on 2021-04-19 16:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('index', '0011_auto_20210408_2224'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('action_date', models.DateTimeField(auto_created=True, default=django.utils.timezone.now, verbose_name='動作日期')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('n', 'notknown'), ('d', 'deleteData'), ('a', 'addData'), ('r', 'reviseData'), ('l', 'loanProperty'), ('r', 'ReturnProperty'), ('i', 'importExcel')], default='n', max_length=1, verbose_name='用戶動作')),
                ('action_user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用戶')),
            ],
        ),
    ]
