# Generated by Django 3.2 on 2021-04-19 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0012_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('r', 'Read'), ('n', 'notRead')], default='n', max_length=1, verbose_name='訊息狀態'),
        ),
    ]
