# Generated by Django 3.2 on 2021-04-20 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('index', '0013_notification_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notify_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.group', verbose_name='群組'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='action',
            field=models.CharField(choices=[('n', 'notknown'), ('d', 'deleteData'), ('a', 'addData'), ('w', 'writeData'), ('l', 'loanProperty'), ('r', 'ReturnProperty'), ('i', 'importExcel')], default='n', max_length=1, verbose_name='用戶動作'),
        ),
    ]
