# Generated by Django 3.2 on 2021-04-20 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0014_auto_20210420_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='group_status',
            field=models.CharField(choices=[('r', 'Read'), ('n', 'notRead')], default='n', max_length=1, verbose_name='群體訊息狀態'),
        ),
    ]
