"""
Django settings for Web project.

Generated by 'django-admin startproject' using Django 3.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""
from pathlib import Path
import os

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""
# Build paths inside the project like this: BASE_DIR / 'subdir'.
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '3q%frfi_urea*^-23@u&1thgjs(w7zqoagkv+f76ch9=o-idap'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

SESSION_EXPIRE_AT_BROWSER_CLOSE = True

SESSION_COOKIE_AGE = 5 * 60 * 60 #

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""
#   Application definition
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'index.apps.IndexConfig',
    'werkzeug_debugger_runserver',
    'django_extensions',
    'channels',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Web.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""
#   Django提供兩種伺服器通道
#   此處選用ASGI
#   支援WebSocket
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""
# WSGI_APPLICATION = 'Web.wsgi.application'
ASGI_APPLICATION = "Web.asgi.application"


"""""""""""""""""""""""""""""""""""""""""""""""""""""""""
#   使用通道層
#   (部屬建議)Redis
#   或者
#   (開發用)記憶體通道
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""
# CHANNEL_LAYERS = {
#     "default": {
#         "BACKEND": "channels_redis.core.RedisChannelLayer",
#         "CONFIG": {
#             "hosts": [("127.0.0.1", 6379)],
#         },
#     },
# }
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer"
    }
}

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""
#   Database
#   https://docs.djangoproject.com/en/3.1/ref/settings/#databases
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'myweb',
        'USER': 'root',
        'PASSWORD': 'root',
        'HOST': 'localhost',
        'PORT': '3306',
    }
}

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""
#   Password validation
#   https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""
#   Internationalization
#   https://docs.djangoproject.com/en/3.1/topics/i18n/
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""
LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Taipei'

USE_I18N = True

USE_L10N = True

USE_TZ = True

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""
#    Static files (CSS, JavaScript, Images)
#   https://docs.djangoproject.com/en/3.1/howto/static-files/
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""
STATIC_URL = '/static/'

STATIC_ROOT = './static_file/'

STATICFILES_DIRS = [
    BASE_DIR / "static"
]

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""
#   Redirect to home URL after login (Default redirects to /accounts/profile/)
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""
LOGIN_REDIRECT_URL = '/'